default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: capstone_development

test:
  <<: *default
  database: capstone_test

production:
  <<: *default
  password: <%= ENV['DATABASE_URL'] %>
